-- GXA Toolbox authentication and processing-history schema.
-- Applied automatically by Netlify Database during deploys.
-- PostgreSQL only; non-destructive and contains no seed users or passwords.

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'user',
    is_premium BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_email_normalized CHECK (email = LOWER(BTRIM(email))),
    CONSTRAINT users_full_name_not_blank CHECK (CHAR_LENGTH(BTRIM(full_name)) >= 2),
    CONSTRAINT users_role_valid CHECK (role IN ('developer', 'admin', 'user')),
    CONSTRAINT users_status_valid CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS public.file_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    tool_name VARCHAR(100) NOT NULL,
    original_file VARCHAR(255) NOT NULL,
    output_file VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'done',
    size_mb NUMERIC(12, 4) NOT NULL DEFAULT 0,
    processing_time_ms INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT file_jobs_user_fk
        FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON DELETE SET NULL,
    CONSTRAINT file_jobs_tool_name_not_blank CHECK (CHAR_LENGTH(BTRIM(tool_name)) > 0),
    CONSTRAINT file_jobs_original_file_not_blank CHECK (CHAR_LENGTH(BTRIM(original_file)) > 0),
    CONSTRAINT file_jobs_output_file_not_blank CHECK (CHAR_LENGTH(BTRIM(output_file)) > 0),
    CONSTRAINT file_jobs_size_nonnegative CHECK (size_mb >= 0),
    CONSTRAINT file_jobs_processing_time_nonnegative CHECK (processing_time_ms >= 0)
);

CREATE INDEX IF NOT EXISTS file_jobs_user_created_idx
    ON public.file_jobs (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS file_jobs_user_status_idx
    ON public.file_jobs (user_id, status);

CREATE OR REPLACE FUNCTION public.gxa_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.gxa_set_updated_at();

DROP TRIGGER IF EXISTS file_jobs_set_updated_at ON public.file_jobs;
CREATE TRIGGER file_jobs_set_updated_at
BEFORE UPDATE ON public.file_jobs
FOR EACH ROW
EXECUTE FUNCTION public.gxa_set_updated_at();
