-- Privacy-minimized internal analytics for the protected GXA admin dashboard.
-- No file names, file contents, OCR text, passwords, session tokens, IP addresses,
-- user agents, or external analytics credentials are stored here.

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.tool_analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    tool_id VARCHAR(100) NOT NULL,
    tool_name VARCHAR(120) NOT NULL,
    tool_category VARCHAR(40) NOT NULL,
    status VARCHAR(40),
    duration_bucket VARCHAR(32),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tool_analytics_event_type_valid CHECK (
        event_type IN ('tool_open', 'tool_start', 'tool_complete', 'tool_fail', 'tool_download')
    ),
    CONSTRAINT tool_analytics_tool_id_valid CHECK (tool_id ~ '^[a-z0-9-]{1,100}$'),
    CONSTRAINT tool_analytics_category_not_blank CHECK (CHAR_LENGTH(BTRIM(tool_category)) > 0)
);

CREATE INDEX IF NOT EXISTS tool_analytics_type_time_idx
    ON public.tool_analytics_events (event_type, occurred_at DESC);

CREATE INDEX IF NOT EXISTS tool_analytics_tool_time_idx
    ON public.tool_analytics_events (tool_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    category VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_event_type_valid CHECK (
        event_type IN ('registration_success', 'registration_failure', 'login_success', 'login_failure', 'session_failure')
    ),
    CONSTRAINT auth_event_category_not_blank CHECK (CHAR_LENGTH(BTRIM(category)) > 0)
);

CREATE INDEX IF NOT EXISTS auth_events_type_time_idx
    ON public.auth_events (event_type, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.system_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    category VARCHAR(80) NOT NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'error',
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_event_severity_valid CHECK (severity IN ('info', 'warning', 'error')),
    CONSTRAINT system_event_source_not_blank CHECK (CHAR_LENGTH(BTRIM(source)) > 0),
    CONSTRAINT system_event_category_not_blank CHECK (CHAR_LENGTH(BTRIM(category)) > 0)
);

CREATE INDEX IF NOT EXISTS system_events_source_time_idx
    ON public.system_events (source, occurred_at DESC);
