-- Persist genuine Contact Support submissions for protected administrator review.
-- This migration is additive and does not modify existing users, jobs, or history.

CREATE TABLE IF NOT EXISTS public.support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_user_id TEXT,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'new',
    dedupe_key CHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT support_messages_identity_user_fk
        FOREIGN KEY (identity_user_id)
        REFERENCES public.user_profiles (identity_user_id)
        ON DELETE SET NULL,
    CONSTRAINT support_messages_name_not_blank CHECK (CHAR_LENGTH(BTRIM(full_name)) BETWEEN 2 AND 120),
    CONSTRAINT support_messages_email_normalized CHECK (email = LOWER(BTRIM(email))),
    CONSTRAINT support_messages_message_length CHECK (CHAR_LENGTH(BTRIM(message)) BETWEEN 10 AND 4000),
    CONSTRAINT support_messages_status_valid CHECK (status IN ('new', 'in_progress', 'resolved'))
);

CREATE INDEX IF NOT EXISTS support_messages_status_created_idx
    ON public.support_messages (status, created_at DESC);

CREATE INDEX IF NOT EXISTS support_messages_identity_created_idx
    ON public.support_messages (identity_user_id, created_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_trigger
         WHERE tgname = 'support_messages_set_updated_at'
           AND tgrelid = 'public.support_messages'::regclass
           AND NOT tgisinternal
    ) THEN
        CREATE TRIGGER support_messages_set_updated_at
        BEFORE UPDATE ON public.support_messages
        FOR EACH ROW
        EXECUTE FUNCTION public.gxa_set_updated_at();
    END IF;
END
$$;
